/*
    Shreya Patel
    1001646429
*/
package advisor;

public class AdvisorGUIHandler extends javax.swing.JFrame {

    static AdvisorHandler advisorHandler;

    /**
     * Creates new form AdvisorGUIHandler
     */
    public AdvisorGUIHandler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        advisorLabel = new javax.swing.JLabel();
        advisorExitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        advisorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        advisorLabel.setForeground(new java.awt.Color(51, 51, 255));
        advisorLabel.setText("Advisor");

        advisorExitButton.setText("Exit");
        advisorExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advisorExitButtonActionPerformed(evt);
            }
        });

        messageBox.setColumns(20);
        messageBox.setRows(5);
        jScrollPane2.setViewportView(messageBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advisorLabel)
                    .addComponent(advisorExitButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advisorLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(advisorExitButton)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void advisorExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advisorExitButtonActionPerformed
        // TODO add your handling code here:
        exitAction();
    }//GEN-LAST:event_advisorExitButtonActionPerformed

    // Close open connections and then UI
    private void exitAction() {
        advisorHandler.disconnect();
        dispose(); // close UI
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvisorGUIHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvisorGUIHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvisorGUIHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvisorGUIHandler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        AdvisorGUIHandler advisorGUIHandler = new AdvisorGUIHandler();
        advisorHandler = new AdvisorHandler(advisorGUIHandler);
        advisorHandler.start();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                advisorGUIHandler.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advisorExitButton;
    private javax.swing.JLabel advisorLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea messageBox;
    // End of variables declaration//GEN-END:variables

    /**
     * Provides method to display message on message box
     */
    public void displayMessageOnUI(String message) {
        if (!message.equals("")) {
            messageBox.append("\n-----------------------------------------------------------------------------------------\n");
            messageBox.append(message);
            messageBox.append("\n-----------------------------------------------------------------------------------------\n");
        }
    }
}
